[package]
name = "vega-node"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
tokio = { version = "1.36", features = ["full"] }
vegastar = { path = "../../lib/vegastar" }
vegagate = { path = "../../lib/vegagate" }
vegastore = { path = "../../lib/vegastore" }
veganet = { path = "../../lib/veganet" }
