[package]
name = "vega-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.36", features = ["full"] }
vegastar = { path = "../../lib/vegastar" }
vegagate = { path = "../../lib/vegagate" }
vegastore = { path = "../../lib/vegastore" }
